---
- name: Determine middle node IP for each edge node
  set_fact:
    middle_host_ip: "{{ middles['middle01-aluvshis-dev'] }}"
  when: "inventory_hostname in ['edge-aluvshis-dev-jp-osa-01']"

- name: Determine middle node IP for each edge node
  set_fact:
    middle_host_ip: "{{ middles['middle02-aluvshis-dev'] }}"
  when: "inventory_hostname in ['edge-aluvshis-dev-in-maa-01']"

- name: Determine proxy node IP for each middle node
  set_fact:
    proxy_ip: "{{ proxies[0] }}"
  when: "'middle01' in inventory_hostname"

- name: Determine proxy node IP for each middle node
  set_fact:
    proxy_ip: "{{ proxies[0] }}"
  when: "'middle02' in inventory_hostname"

- name: Copy ProxyProtocol to Sketch Nodes
  copy:
    src: files/install_ProxyProtocol.sh
    dest: "{{ ansible_user_dir }}/install_ProxyProtocol.sh"
    mode: 0755  

- name: Run ProxyProtocol on Edge nodes
  become: yes
  shell: "./install_ProxyProtocol.sh {{ middle_host_ip }} edge"
  when: "'edge' in inventory_hostname"

- name: Run ProxyProtocol on Middle nodes
  become: yes
  shell: "./install_ProxyProtocol.sh {{ proxy_ip }} middle"
  when: "'middle' in inventory_hostname"
