---
# tasks file for backflips-v2
- name: Create flip group
  group:
    name: flip
    state: present
    system: true

- name: Create flip user
  user:
    name: flip
    group: flip
    state: present
    system: true
    create_home: false
    home: /opt/backflips
    shell: /usr/sbin/nologin

- name: Create home
  file:
    path: /opt/backflips
    owner: flip
    group: flip
    mode: 0755
    state: directory

- name: Copy files to host
  copy:
    src: files/flip_files/
    dest: /opt/backflips/
    owner: flip
    group: flip

- name: Generate rsa keypairs
  community.crypto.openssh_keypair:
    path: "/opt/backflips/etc/ssh/ssh_host_rsa_key_{{ item }}"
    type: rsa
    size: 4096
    group: flip
    owner: flip
  loop: "{{ ports }}"

- name: Generate ed25519 keypairs
  community.crypto.openssh_keypair:
    path: "/opt/backflips/etc/ssh/ssh_host_ed25519_key_{{ item }}"
    type: ed25519
    owner: flip
    group: flip
  loop: "{{ ports }}"

- name: Configure SSHd Configuration File
  template:
    src: sshd_config.j2
    dest: "/opt/backflips/etc/ssh/sshd_config_{{ item }}"
    mode: 0644
    owner: root
  loop: "{{ ports }}"

- name: Configure Containers
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/backflips
    mode: 0644
    owner: root
    

#- name: Deploy Dockerized SSH Servers
#  docker_container:
#    name: "backflip_{{ item }}"
#    image: "linuxserver/openssh-server:latest"
#    state: started
#    restart_policy: always
#    published_ports:
#      - "{{ item }}:22"
#    env:
#      USERNAME: "{{ ssh_user }}"
#    volumes:
#      - "/opt/backflips/etc/ssh/ssh_host_rsa_key_{{ item }}:/etc/ssh/ssh_host_rsa_key"
#      - "/opt/backflips/etc/ssh/ssh_host_ed25519_key_{{ item }}:/etc/ssh/ssh_host_ed25519_key"
#      - "/opt/backflips/etc/ssh/sshd_config_{{ item }}:/etc/ssh/sshd_config"
#  loop: "{{ ports }}"
#  become: true