---
# tasks file for backflips-v2
- name: Create flip group
  group:
    name: flip
    state: present
    system: true

- name: Create flip user
  user:
    name: flip
    group: flip
    state: present
    system: true
    create_home: false
    home: /opt/backflips
    shell: /usr/sbin/nologin

- name: Create home
  file:
    path: /opt/backflips
    owner: flip
    group: flip
    mode: 0755
    state: directory

- name: Copy files to host
  copy:
    src: files/flip_files/
    dest: /opt/backflips/
    owner: flip
    group: flip

- name: Ensure backflips SSH directory exists
  file:
    path: "/opt/backflips/etc/ssh"
    state: directory
    owner: flip
    group: flip
    mode: '0755'

- name: Copy SSHd Configure
  copy:
    src: files/etc/ssh/sshd_config
    dest: /opt/backflips/etc/ssh/config
    owner: flip
    group: flip

- name: Generate rsa keypairs
  community.crypto.openssh_keypair:
    path: "/opt/backflips/etc/ssh/ssh_host_rsa_key_{{ item }}"
    type: rsa
    size: 4096
    group: flip
    owner: flip
  loop: "{{ domain_names }}"

- name: Generate ed25519 keypairs
  community.crypto.openssh_keypair:
    path: "/opt/backflips/etc/ssh/ssh_host_ed25519_key_{{ item }}"
    type: ed25519
    owner: flip
    group: flip
  loop: "{{ domain_names }}"

- name: Configure Dockerfiles
  template:
    src: templates/Dockerfile.j2
    dest: "/opt/backflips/Dockerfile_{{ item }}"
    owner: flip
    mode: 0644
  loop: "{{ domain_names }}"

- name: Configure Containers
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/backflips/docker-compose.yml
    mode: 0644
    owner: flip

- name: Set Ownership and Perms
  ansible.builtin.file:
    path: /opt/backflips
    owner: flip
    group: flip
    mode: '0755'
    recurse: yes

- name: Set Key Perms
  ansible.builtin.file:
    path: /opt/backflips/etc/ssh
    owner: flip
    group: flip
    mode: '0600'
    recurse: yes

- name: Check for OpenSSH Docker Image
  docker_image:
    name: lscr.io/linuxserver/openssh-server:latest
    source: pull
  register: docker_image_pull
  ignore_errors: yes

- name: Start containers
  command: docker compose -f /opt/backflips/docker-compose.yml up -d
  args:
    chdir: /opt/backflips